use TFM;

CREATE TABLE `USUARIO` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Nombre` VARCHAR(50) NOT NULL,
	`Usuario` VARCHAR(50) NOT NULL,
	`Password` VARCHAR(50) NOT NULL,
	`Correo` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8mb4_general_ci';

CREATE TABLE `CANCION` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Titulo` VARCHAR(50) NOT NULL,
	`Fecha` DATE NOT NULL,
	`Procesado` BOOLEAN NOT NULL,
	`Estilo` VARCHAR(50) NOT NULL,
	`Usuario` INT NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `FKUSUARIO` FOREIGN KEY (`Usuario`) REFERENCES `USUARIO` (`ID`)
)
COLLATE='utf8mb4_general_ci';

CREATE TABLE `FICHERO` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Fichero` BLOB NOT NULL,
	`Cancion` INT NOT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `FKCANCION` FOREIGN KEY (`Cancion`) REFERENCES `CANCION` (`ID`)
)
COLLATE='utf8mb4_general_ci';
